/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de5;

import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author phamt
 */
public class Form5 extends javax.swing.JFrame {

    /**
     * Creates new form Form5
     */
    public Form5() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rbtat = new javax.swing.JRadioButton();
        rbtmm = new javax.swing.JRadioButton();
        txtmasv = new javax.swing.JTextField();
        txthoten = new javax.swing.JTextField();
        txtngaysinh = new javax.swing.JTextField();
        txtdtb = new javax.swing.JTextField();
        txtdonvi = new javax.swing.JTextField();
        rbtnam = new javax.swing.JRadioButton();
        rbtnu = new javax.swing.JRadioButton();
        txtluong = new javax.swing.JTextField();
        txthocphi = new javax.swing.JTextField();
        btsave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Form nhập thông tin");

        jLabel2.setText("Loại sinh viên");

        jLabel3.setText("Mã sinh viên");

        jLabel4.setText("Họ tên");

        jLabel5.setText("Ngày sinh");

        jLabel6.setText("Điểm trung bình");

        jLabel7.setText("Giới tính");

        jLabel8.setText("Học phí");

        jLabel9.setText("Đơn vị");

        jLabel10.setText("Lương");

        buttonGroup1.add(rbtat);
        rbtat.setText("SVATTT");
        rbtat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtatActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtmm);
        rbtmm.setText("SVMM");
        rbtmm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtmmActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtnam);
        rbtnam.setText("Nam");

        buttonGroup2.add(rbtnu);
        rbtnu.setText("Nữ");

        btsave.setText("Save");
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel8)))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rbtnam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtnu))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rbtat)
                        .addGap(64, 64, 64)
                        .addComponent(rbtmm))
                    .addComponent(txtmasv)
                    .addComponent(txthoten)
                    .addComponent(txtngaysinh)
                    .addComponent(txtdtb)
                    .addComponent(txtdonvi)
                    .addComponent(txtluong)
                    .addComponent(txthocphi))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btsave)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbtat)
                    .addComponent(rbtmm))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtmasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtdtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rbtnam)
                    .addComponent(rbtnu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtdonvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txthocphi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btsave)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtatActionPerformed
       txthocphi.setEnabled(true);
       txtdonvi.setEnabled(false);
       txtluong.setEnabled(false);
    }//GEN-LAST:event_rbtatActionPerformed

    private void rbtmmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtmmActionPerformed
       txthocphi.setEnabled(false);
       txtdonvi.setEnabled(true);
       txtluong.setEnabled(true);
    }//GEN-LAST:event_rbtmmActionPerformed

    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed
        if((!rbtat.isSelected())&&(!rbtmm.isSelected())) 
        {
                    JOptionPane.showMessageDialog(null, "Bạn phải chọn loại sinh viên");
        }
        else if (rbtat.isSelected())
        {
            if(ktnhapantoan()==true)
            {
                try
                {
                    //Khởi tạo đối tượng
                SinhvienATTT svat = new SinhvienATTT(Float.parseFloat(txthocphi.getText()), txtmasv.getText(), txthoten.getText(), txtngaysinh.getText(), rbtnam.isSelected()? "Nam":"Nữ", Float.parseFloat(txtdtb.getText()));
                FileWriter fw = new FileWriter("C:\\test\\svat.dat");
                BufferedWriter bw = new BufferedWriter(fw);
                bw.append(svat.masv +"$" +svat.hoten +"$"+svat.ngaysinh+"$"+svat.dtb+"$"+svat.gioitinh+"$"+svat.getHocphi());
                bw.close();
                fw.close();
                JOptionPane.showMessageDialog(null, "Lưu file cho sinh viên an toàn thành công");
                }
                catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null, "Lưu file thất bại");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ thông tin");
                return;
            }
        }
        else
        {
            if(ktnhapmatma()==true)
            {
                try
                {
                    // Khởi tạo đối tượng
                SinhvienMatMa svmm = new SinhvienMatMa(txtdonvi.getText(),Float.parseFloat(txtluong.getText()), txtmasv.getText(), txthoten.getText(), txtngaysinh.getText(), rbtnam.isSelected()? "Nam":"Nữ", Float.parseFloat(txtdtb.getText()));
                FileWriter fw = new FileWriter("C:\\test\\svmm.dat");
                BufferedWriter bw = new BufferedWriter(fw);
                bw.append(svmm.masv +"$" +svmm.hoten +"$"+svmm.ngaysinh+"$"+svmm.dtb+"$"+svmm.gioitinh+"$"+svmm.getDonvi()+"$"+svmm.getLuong());
                bw.close();
                fw.close();
                JOptionPane.showMessageDialog(null, "Lưu file cho sinh viên mật mã thành công");          
                }
                catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null, "Lưu file thất bại");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ thông tin");
                return;
            }
        }
        

    }//GEN-LAST:event_btsaveActionPerformed

    public boolean ktnhapantoan()
    {
        if( txtmasv.getText().equals("") || txthoten.getText().equals("") ||  txtngaysinh.getText().equals("") || txtdtb.getText().equals("") ||(!rbtnam.isSelected()&&!rbtnu.isSelected())  || txthocphi.getText().equals(""))
        {
            return false;
        }
        return true;

    }
    
    public boolean ktnhapmatma()
    {
        if( txtmasv.getText().equals("") || txthoten.getText().equals("") ||  txtngaysinh.getText().equals("") || txtdtb.getText().equals("") ||(!rbtnam.isSelected()&&!rbtnu.isSelected()) || txtdonvi.getText().equals("") || txtluong.getText().equals(""))
        {
            return false;
        }
        return true;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btsave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbtat;
    private javax.swing.JRadioButton rbtmm;
    private javax.swing.JRadioButton rbtnam;
    private javax.swing.JRadioButton rbtnu;
    private javax.swing.JTextField txtdonvi;
    private javax.swing.JTextField txtdtb;
    private javax.swing.JTextField txthocphi;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtluong;
    private javax.swing.JTextField txtmasv;
    private javax.swing.JTextField txtngaysinh;
    // End of variables declaration//GEN-END:variables
}
